### ISSUE TITLE
cannot open source file "filesystem" and "experimental/filesystem"

### ISSUE THREAD

**Issue by wolfram-schmidt** [parthenon-hpc-lab/athenapk#103]
CMake fails with

CMake Error at external/parthenon/cmake/FindFilesystem.cmake:254 (message):
  Cannot Compile simple program using std::filesystem

using Intel compilers/mpi 2021.2 with the config file 

```
message(STATUS "Loading machine configuration for HLRN-IV supercomputer using Intel modules.")

# Kokkos settings
set(Kokkos_ARCH_SKX ON CACHE BOOL "Target Skylake")

# Intel compiler
set(CMAKE_CXX_COMPILER mpiicpc CACHE STRING "")
set(CMAKE_C_COMPILER mpiicc CACHE STRING "")
```

Complete output in build directory is attached.

[build-mpi.tar.gz](https://github.com/parthenon-hpc-lab/athenapk/files/14510542/build-mpi.tar.gz)

**Comment by pgrete** [comment]
Not sure why this fails. Following https://github.com/vector-of-bool/CMakeCM/blob/master/modules/FindFilesystem.cmake maybe adding a `-lstdc++fs` parameter, i.e., `-DCMAKE_CXX_FLAGS=-lstdc++fs` might help.
Alternatively, it may be worth to try the new Intel stack, i.e., `icpx` as compiler.

**Comment by wolfram-schmidt** [comment]
Seems that there is no stdc++fs library:
```
/sw/tools/oneapi/2022.2/mpi/2021.6.0/bin/mpiicpc  -qopenmp-simd -lstdc++fs  CMakeFiles/cmTC_7e8e2.dir/testCXXCompiler.cxx.o -o cmTC_7e8e2 
    ld: cannot find -lstdc++fs
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
Something to request from the software admins?

Also tried icp and icpx, but that doesn't change anything.

**Comment by forrestglines** [comment]
Probably something to ask from the admins?

You could try looking for that library in the directory where you find your intel compiler. 
```
find /usr/lib/ -name "*c++fs*"
```


Some ancient documentation suggests that library used to be called just `c++fs` for `llvm8.0`, so you could see if linking to that works
```
ld -lc++fs
```

**Comment by pgrete** [comment]
Great. I'm happy to hear this is resolved.
