### ISSUE TITLE
update parthenon to commit 314ac5c for easier debugging

### ISSUE THREAD

**Issue by BenWibking** [parthenon-hpc-lab/athenapk#104]
It would be *very* useful to update the Partheon submodule to this commit:
https://github.com/parthenon-hpc-lab/parthenon/commit/314ac5c03178748c17161ce691ef24d535f0b539

**Comment by BenWibking** [comment]
@pgrete Do you know if any unrelated changed affect our ability to fast-forward to this commit?

**Comment by pgrete** [comment]
> @pgrete Do you know if any unrelated changed affect our ability to fast-forward to this commit?

No. Go for it.
