### ISSUE TITLE
Build error when using cuda

### ISSUE THREAD

**Issue by tbhaxor** [parthenon-hpc-lab/athenapk#17]
I have used the following command to build the project for cuda

```bash
cmake -Bbuild-gpu -DKokkos_ARCH_TURING75=ON  -DKokkos_ENABLE_CUDA=ON  -DCUDA_ROOT=/opt/cuda
make -j $(nproc)
```

now it is failing at

```
/usr/include/c++/12.2.1/bits/locale_facets_nonio.tcc: In member function ‘_InIter std::__cxx11::time_get<_CharT, _InIter>::get(iter_type, iter_type, std::ios_base&, std::ios_base::iostate&, tm*, const char_type*, const char_type*) const’:
/usr/include/c++/12.2.1/bits/locale_facets_nonio.tcc:1477:77: error: invalid type argument of unary ‘*’ (have ‘int’)
 1477 |       if ((void*)(this->*(&time_get::do_get)) == (void*)(&time_get::do_get))
      | 
```

Is it specific to g++ version, if yes which one is recommended?

**Comment by pgrete** [comment]
You can find a GCC compatibility list here: https://gist.github.com/ax3l/9489132

If an older GCC doesn't work it'd be good if you could post the full output of your initial cmake command so that we can see all version details found in that stage.

**Comment by tbhaxor** [comment]
Thanks for this, regarding the kokkos arch for geforce gtx 1650, it is indeed based on [turing arch](https://forums.developer.nvidia.com/t/cuda-enabled-geforce-1650/81010/10)

Had this discussion on the gitlab repo

**Comment by tbhaxor** [comment]
Fixed, g++11 is used
