### ISSUE TITLE
CMake warning: empty CUDA_ARCHITECTURES not allowed

### ISSUE THREAD

**Issue by BenWibking** [parthenon-hpc-lab/athenapk#30]
Not sure if this is a Parthenon issue or AthenaPK issue. Only appears with very recent versions of CMake.

```
CMake Warning (dev) in src/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "athenaPK".
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by pgrete** [comment]
I came across that one, too.
Given that it also showed for Ascent, I expect this a more common "issue"  with a simple fix (though I didn't investigate yet).

**Comment by BenWibking** [comment]
Should I move this issue to Parthenon?

**Comment by pgrete** [comment]
Yes, I think this should be fixed upstream.

**Comment by BenWibking** [comment]
Closing in favor of https://github.com/parthenon-hpc-lab/parthenon/issues/845.
