### ISSUE TITLE
Need explanation of use of the enum used in the code base

### ISSUE THREAD

**Issue by tbhaxor** [parthenon-hpc-lab/athenapk#43]
https://github.com/parthenon-hpc-lab/athenapk/blob/693c641aa669f829c8616a58fcd6b03a7a99c6dd/src/main.hpp#L17-L28

**Comment by BenWibking** [comment]
They are the indices of the variables in the hydro (or MHD) equations as stored in the arrays used in the code.

In Athena++, they are here: https://github.com/PrincetonUniversity/athena/blob/cf41e30125fe40ac302c53aeb860a706e7ba1e0a/src/athena.hpp#L136.

**Comment by tbhaxor** [comment]
Thanks. I checked the examples they all take conserved variables.
