### ISSUE TITLE
Origin of Schure cooling table

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/athenapk#9]
Where does the data in the Schure cooling table actually come from, @forrestglines ?
The comment say
```
# Cooling table for solar metallicity, 1/2 solar metallicity
#   (from Chris Loken, computed with Sarazin & White's analytic expression)
#  temperature if log(K), cooling rate/ne^3 (erg cm^3/s)
# This is the new cooling table based on http://arxiv.org/pdf/0909.5204v2
```
but when I look at the pdf
a) there are slight discrepancies in the numbers for solar metallicity (table 2)
b) there's no table for the half-solar metallicity column

To be clear, I'm not concerned that those numbers are "wrong" (or that the slight deviation have a significant impact), I just want to understand where they come from.

**Comment by forrestglines** [comment]
That cooling table was given to me when I started at MSU along with other initial parameters for Enzo. It's also not included inside Enzo so I assume it's just one of those files that tend to be passed around developers without much thought. If we can't figure out where it comes from, we should remove it from the repo.

Brian might know where that file comes from.

**Comment by pgrete** [comment]
> Brian might know where that file comes from.

In this case, ping @bwoshea

**Comment by BenWibking** [comment]
This issue is fixed by https://github.com/parthenon-hpc-lab/athenapk/pull/97.
